# Copyright The Kubernetes Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: Deployment to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main 
    paths: 
      - 'site/**'
      - '.github/workflows/deploy-github-pages.yml'
  pull_request:
    # This allows PRs to trigger the BUILD job to ensure the site compiles, 
    # but it will skip the DEPLOY job.
    paths:
      - 'site/**'
      - '.github/workflows/deploy-github-pages.yml'

permissions:
  contents: read
  pages: write
  id-token: write

env:
  REPO_NAME: ${{ github.event.repository.name }}
  REPO_OWNER: ${{ github.repository_owner }}

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # JOB 1: Build the site (Runs on Push and PR)
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # v3
        with:
          hugo-version: '0.125.5'
          extended: true

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v4
        with:
          node-version: '20'
          check-latest: true

      - run: |
          npm init --yes
          npm install --save-dev autoprefixer postcss-cli
        working-directory: ./site

      - run: hugo --baseURL https://dranet.sigs.k8s.io --minify
        working-directory: ./site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site/public

  # JOB 2: Deploy the site (Runs ONLY on Push to main)
  deploy:
    # Requires the 'build' job to finish successfully first
    needs: build 
    # Ensures this only deploys if it's a push to the main branch (skips PRs)
    if: github.ref == 'refs/heads/main'
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4