name: Helm Lint
on:
  pull_request:
    branches: [ main ]
    paths:
      - 'deployments/helm/**'
      - '.github/workflows/helm-lint.yml'

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Run Helm lint
        run: make helm-lint
